utilisateur_utilisateur:
    resource: "@UtilisateurUtilisateurBundle/Controller/"
    type:     annotation
    prefix:   /utilisateur

acme_ecommerce:
    resource: "@AcmeEcommerceBundle/Controller/"
    type:     annotation
    prefix:   /ecommerce

acme_test:
    resource: "@AcmeTestBundle/Controller/"
    type:     annotation
    prefix:   /test

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

# app_file:
#     # loads routes from the given routing file stored in some bundle
#     resource: '@AcmeBlogBundle/Resources/config/routing.yaml'
